server:
  port: 9191

# 扳手通用组件配置
xyf:
  wrench:
    config:
      system: test-system
      register:
        # redis host
        host: 127.0.0.1
        # redis port
        port: 16379

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml